### PR TITLE
added a funny line

### PR DESCRIPTION
**Pull request by tiffanywilson**

### CODE REVIEW

**Comment by 1egoman** [comment]
@tiffanywilson Could you fix the merge conflict? Thanks for adding a funny line!

**Comment by tiffanywilson** [comment]
@1egoman resolved

**Comment by 1egoman** [comment]
@tiffanywilson I'm really sorry, but I think I caused another conflict. If you'd be willing to fix it again I'll make sure to merge yours in first next time as to not cause any more trouble.

Thanks!

**Comment by tiffanywilson** [comment]
@1egoman no worries! fixed again

**Comment by 1egoman** [comment]
Thanks! 😄

**Pull request merged**
