### PR TITLE
Add more funnies

### PR DESCRIPTION
**Pull request by tadityar**
Per issue #6 can adding more funnies!

### CODE REVIEW

**Comment by 1egoman** [comment]
@tadityar Could you add a comma to the 2nd-to-last line to make ci pass? Thanks!

**Comment by 1egoman** [comment]
@tadityar Oops, I just notices there's a merge conflict. Would you be able to fix it?

**Comment by tadityar** [comment]
Hi! Sorry I've been busy haha, I've resolved the merge conflict.

Cheers!

**Comment by 1egoman** [comment]
:D Thanks!

**Pull request merged**
