### PR TITLE
Angular2 component for funnies

### PR DESCRIPTION
**Pull request by david1983**
Hi there,
I've pushed the angular2 component in /src.
and the demo in /angular, I've done the scaffold using "angular-cli" so in order to run it you need to install the cli with npm. I don't have the minimum idea how to do it without the cli :), this is my first project in angular2 so, please if you find some errors, or something that can be done in a better way, just let me know.

Following are the commands to install the cli and the dependencies, I left the original readme of the angular-cli inside the folder btw

`npm install -g angular-cli`
`npm install` - in the angular directory
`ng serve` - serve the project
`ng build` - build the project into /dist

### CODE REVIEW

**Comment by 1egoman** [comment]
@david1983 I will look at this over the weekend. Thanks for working on this!

**Comment by 1egoman** [comment]
@david1983

This is great! A few simple things I'd like you to fix, though:

1. I'd prefer you consume the pre-built funnies class rather than picking messages yourself right from the array. The pre-built class does a few fancy things to make sure that repeat messages wont be generated while still generating them in a random order. [usage example](https://github.com/1egoman/funnies#usage)

2. Could you create an examples directory and put the angular example within it? Something like:
```
funnies/
├── examples/
│   ├── angular/
│   │   ├── (your example code goes here)
│   └── (I'll stick some more examples in here later)
```

3. I'm currently working on removing the `Loading` text from the integrations that have been written so far (`react`/`jquery`). The reasoning behind this is that pushing users into a predefined format isn't a good idea (https://github.com/1egoman/funnies/issues/1#issuecomment-249426739). For example, [here's what I did to the react component](https://github.com/1egoman/funnies/commit/f22810cb0d8ad1d717318898af1388391cbd5d65#diff-197182d441b8aa6c80025426a275965dR26). (The animation you're using is great though, and I'm working on re-implementing that in react, so pardon that inconsistency in the example I provided.)

4. What's happening with `(this.interval/5)*4`? Won't that skew the user's specified interval?
5. By default the interval of messages that I've used everywhere else is 8 seconds - could you use that as the default too?

Other than the above, I can't wait to merge this in! Thanks for all your hard work so far!

**Comment by david1983** [comment]
Hi, I'm glad you like it.
I'll do the changes tonight.
About the interval thingy, I changed it in my last commit to be ( interval - animation_duration). I think it should be nice to have a property (or maybe two: in out) to set the animation duration, not sure if it's possible using the animation framework provided by angular2, but I'm sure you can in React.

**Comment by 1egoman** [comment]
@david1983 Great idea! That should be pretty easy to do in react, and if someone else doesn't tackle it I'll probably get to it eventually. ([issue](https://github.com/1egoman/funnies/issues/69))

**Comment by david1983** [comment]
-created directory examples and moved angular demo in
-changed the component to use the Funnies class implementation
-default interval to 8000
-Removed the Loading title
-Changed the component to be a span element, like the React implementation
-Removed styles from the component
-changed the demo accordingly, because now the component is without any style, the style is applied to the parent component .

I'll ask a question on stackoverflow because I cannot find a way to modify the transition duration property at runtime, I think is probably something that I'm missing with the Decorators in Angular2.

**Comment by 1egoman** [comment]
@david1983 Could you stick an example in the readme similar to the react component? Sorry for the last-minute ask.

**Pull request closed without merging**
